test_projects = [
    {
        'project_name': 'Финансовая аналитическая платформа',
        'programming_language': 'Python',
        'architecture': 'MVC',
        'description': 'Веб-платформа для анализа финансовых данных с хранением в базе данных и REST API. Коммерческий проект для банковского сектора с требованиями высокой производительности. Используется машинное обучение для прогнозирования рынков.',
        'performance_requirements': 'Высокая производительность для анализа в реальном времени',
        'security_requirements': 'Шифрование и безопасная аутентификация',
        'project_status': 'in development',
        'version': '1.0'
    },
    {
        'project_name': 'Мобильное приложение для здоровья',
        'programming_language': 'JavaScript',
        'architecture': 'SPA',
        'description': 'Мобильное приложение для отслеживания показателей здоровья с синхронизацией данных через REST API. Функциональное программирование, медицинский сектор. Интеграция с wearable устройствами.',
        'performance_requirements': 'Оптимизация для мобильных устройств',
        'security_requirements': 'Защита медицинских данных',
        'project_status': 'active',
        'version': '2.1'
    },
    {
        'project_name': 'Государственный портал услуг',
        'programming_language': 'Java',
        'architecture': 'Microservices',
        'description': 'Портал государственных услуг с интеграцией различных ведомств. Требуется открытый исходный код, высокая безопасность. Обработка персональных данных граждан.',
        'performance_requirements': 'Высокая доступность',
        'security_requirements': 'Сертификация ФСТЭК, шифрование данных',
        'project_status': 'in development',
        'version': '1.0'
    },
    {
        'project_name': 'Высоконагруженный REST API сервис',
        'programming_language': 'C#',
        'architecture': 'REST API',
        'description': 'Микросервис для обработки высоконагруженных HTTP запросов с интеграцией с базой данных. Коммерческий проект. Реализация асинхронных операций.',
        'performance_requirements': 'Обработка 10000+ запросов в секунду',
        'security_requirements': 'OAuth 2.0, JWT, защита от DDoS',
        'project_status': 'in development',
        'version': '1.5'
    },
    {
        'project_name': 'Интернет-магазин электроники',
        'programming_language': 'JavaScript',
        'architecture': 'MERN Stack',
        'description': 'Полнофункциональный интернет-магазин с системой рекомендаций на основе AI. Интеграция с платежными системами. Progressive Web App для мобильных пользователей.',
        'performance_requirements': 'Быстрая загрузка страниц, кэширование',
        'security_requirements': 'PCI DSS compliance, защита платежей',
        'project_status': 'active',
        'version': '4.0'
    },
    {
        'project_name': 'IoT платформа для умного дома',
        'programming_language': 'Python',
        'architecture': 'Event-driven',
        'description': 'Платформа для управления устройствами умного дома через веб-интерфейс и мобильное приложение. Асинхронная обработка событий. Интеграция с голосовыми помощниками.',
        'performance_requirements': 'Низкая задержка, обработка в реальном времени',
        'security_requirements': 'Шифрование IoT устройств, безопасное обновление',
        'project_status': 'in development',
        'version': '1.0'
    },
    {
        'project_name': 'Образовательная платформа с VR',
        'programming_language': 'JavaScript',
        'architecture': 'JAMStack',
        'description': 'Онлайн платформа для дистанционного обучения с интерактивными курсами и VR компонентами. Система тестирования и аналитики успеваемости.',
        'performance_requirements': 'Потоковое видео, 3D графика',
        'security_requirements': 'Защита персональных данных, DRM',
        'project_status': 'active',
        'version': '2.3'
    },
    {
        'project_name': 'Блокчейн платформа для supply chain',
        'programming_language': 'Java',
        'architecture': 'Blockchain',
        'description': 'Децентрализованная платформа для отслеживания цепочек поставок. Смарт-контракты для автоматизации процессов. Коммерческий проект для логистических компаний.',
        'performance_requirements': 'Высокая пропускная способность транзакций',
        'security_requirements': 'Криптографическая защита, immutable ledger',
        'project_status': 'in development',
        'version': '1.2'
    },
    {
        'project_name': 'Система компьютерного зрения для производства',
        'programming_language': 'Python',
        'architecture': 'Client-Server',
        'description': 'Система для автоматического контроля качества на производственной линии с использованием компьютерного зрения. Deep learning модели для обнаружения дефектов.',
        'performance_requirements': 'Обработка видео в реальном времени',
        'security_requirements': 'Защита интеллектуальной собственности',
        'project_status': 'active',
        'version': '3.1'
    },
    {
        'project_name': 'Многопользовательская онлайн игра',
        'programming_language': 'C#',
        'architecture': 'Client-Server',
        'description': 'Многопользовательская RPG игра с открытым миром. Реализация на Unity с серверной частью на .NET. Система микротранзакций и социальных функций.',
        'performance_requirements': 'Низкая задержка, синхронизация игрового мира',
        'security_requirements': 'Защита от читов, безопасность платежей',
        'project_status': 'in development',
        'version': '0.8'
    },
    {
        'project_name': 'Система управления складом',
        'programming_language': 'Java',
        'architecture': 'Monolith',
        'description': 'Корпоративная система управления складскими запасами и логистикой. Интеграция с ERP системами. Генерация отчетов и аналитика.',
        'performance_requirements': 'Обработка большого количества транзакций',
        'security_requirements': 'Ролевая модель доступа, аудит действий',
        'project_status': 'active',
        'version': '5.2'
    },
    {
        'project_name': 'Платформа для Data Science исследований',
        'programming_language': 'Python',
        'architecture': 'Jupyter-based',
        'description': 'Облачная платформа для проведения Data Science экспериментов. Поддержка Jupyter ноутбуков, версионирование моделей, распределенные вычисления.',
        'performance_requirements': 'Вычисления на GPU, большие объемы памяти',
        'security_requirements': 'Изоляция сред, защита данных',
        'project_status': 'in development',
        'version': '2.0'
    },
    {
        'project_name': 'Мобильный банкинг',
        'programming_language': 'JavaScript',
        'architecture': 'Cross-platform',
        'description': 'Мобильное приложение для банковских операций. React Native для кроссплатформенной разработки. Биометрия для аутентификации.',
        'performance_requirements': 'Быстрый отклик, оптимизация батареи',
        'security_requirements': 'Банковский уровень безопасности, шифрование',
        'project_status': 'active',
        'version': '3.5'
    },
    {
        'project_name': 'Система мониторинга IT инфраструктуры',
        'programming_language': 'Go',
        'architecture': 'Microservices',
        'description': 'Распределенная система мониторинга серверов, сетей и приложений. Сбор метрик, алертинг, дашборды. Интеграция с популярными системами мониторинга.',
        'performance_requirements': 'Обработка миллионов метрик в минуту',
        'security_requirements': 'TLS шифрование, аутентификация',
        'project_status': 'in development',
        'version': '1.1'
    },
    {
        'project_name': 'Платформа электронного голосования',
        'programming_language': 'Python',
        'architecture': 'Blockchain',
        'description': 'Система для проведения безопасных электронных выборов. Использование блокчейна для обеспечения прозрачности и неизменности результатов.',
        'performance_requirements': 'Масштабируемость для миллионов пользователей',
        'security_requirements': 'Криптография, анонимность, верификация',
        'project_status': 'active',
        'version': '2.0'
    },
    {
        'project_name': 'AI ассистент для поддержки клиентов',
        'programming_language': 'Python',
        'architecture': 'Serverless',
        'description': 'Чат-бот с искусственным интеллектом для автоматизации поддержки клиентов. NLP для понимания запросов, интеграция с CRM.',
        'performance_requirements': 'Низкая задержка ответов',
        'security_requirements': 'Защита персональных данных клиентов',
        'project_status': 'in development',
        'version': '1.3'
    },
    {
        'project_name': 'Система управления контентом для медиа',
        'programming_language': 'JavaScript',
        'architecture': 'Headless CMS',
        'description': 'Современная CMS для медиа-компаний с headless архитектурой. Поддержка мультимедиа контента, версионирование, workflow утверждения.',
        'performance_requirements': 'Быстрая доставка контента, кэширование',
        'security_requirements': 'Управление доступом, защита контента',
        'project_status': 'active',
        'version': '6.1'
    },
    {
        'project_name': 'Платформа для трейдинга криптовалют',
        'programming_language': 'Java',
        'architecture': 'Event Sourcing',
        'description': 'Высокочастотная торговая платформа для криптовалютных бирж. Реализация сложных торговых стратегий, анализ рынка в реальном времени.',
        'performance_requirements': 'Микросекундная задержка',
        'security_requirements': 'Финансовая безопасность, защита от атак',
        'project_status': 'in development',
        'version': '2.4'
    },
]

sample_libraries = [
    # ========== PYTHON БИБЛИОТЕКИ ==========
    {
        'library_name': 'SQLAlchemy',
        'version': '2.0.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'SQLAlchemy Team',
        'repo_url': 'https://github.com/sqlalchemy/sqlalchemy'
    },
    {
        'library_name': 'Django',
        'version': '4.2.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Django Software Foundation',
        'repo_url': 'https://github.com/django/django'
    },
    {
        'library_name': 'Flask',
        'version': '2.3.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Pallets Team',
        'repo_url': 'https://github.com/pallets/flask'
    },
    {
        'library_name': 'FastAPI',
        'version': '0.95.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'FastAPI Team',
        'repo_url': 'https://github.com/tiangolo/fastapi'
    },
    {
        'library_name': 'Requests',
        'version': '2.31.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'http client',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Python Software Foundation',
        'repo_url': 'https://github.com/psf/requests'
    },
    {
        'library_name': 'Pandas',
        'version': '2.0.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'data analysis',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Pandas Team',
        'repo_url': 'https://github.com/pandas-dev/pandas'
    },
    {
        'library_name': 'NumPy',
        'version': '1.24.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'scientific computing',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'NumPy Team',
        'repo_url': 'https://github.com/numpy/numpy'
    },
    {
        'library_name': 'SciPy',
        'version': '1.10.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'scientific computing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'SciPy Team',
        'repo_url': 'https://github.com/scipy/scipy'
    },
    {
        'library_name': 'Scikit-learn',
        'version': '1.2.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'machine learning',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Scikit-learn Team',
        'repo_url': 'https://github.com/scikit-learn/scikit-learn'
    },
    {
        'library_name': 'TensorFlow',
        'version': '2.12.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'deep learning',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Google',
        'repo_url': 'https://github.com/tensorflow/tensorflow'
    },
    {
        'library_name': 'PyTorch',
        'version': '2.0.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'deep learning',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Facebook AI Research',
        'repo_url': 'https://github.com/pytorch/pytorch'
    },
    {
        'library_name': 'Keras',
        'version': '2.12.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'deep learning',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Google',
        'repo_url': 'https://github.com/keras-team/keras'
    },
    {
        'library_name': 'Matplotlib',
        'version': '3.7.0',
        'compatibility': 'Python',
        'license': 'PSF',
        'category': 'data visualization',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Matplotlib Team',
        'repo_url': 'https://github.com/matplotlib/matplotlib'
    },
    {
        'library_name': 'Seaborn',
        'version': '0.12.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'data visualization',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Seaborn Team',
        'repo_url': 'https://github.com/mwaskom/seaborn'
    },
    {
        'library_name': 'Plotly',
        'version': '5.14.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'data visualization',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Plotly Team',
        'repo_url': 'https://github.com/plotly/plotly.py'
    },
    {
        'library_name': 'Celery',
        'version': '5.3.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'task queue',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Celery Team',
        'repo_url': 'https://github.com/celery/celery'
    },
    {
        'library_name': 'Redis',
        'version': '4.5.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'caching',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Redis Team',
        'repo_url': 'https://github.com/redis/redis-py'
    },
    {
        'library_name': 'PyTest',
        'version': '7.3.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'PyTest Team',
        'repo_url': 'https://github.com/pytest-dev/pytest'
    },
    {
        'library_name': 'Selenium',
        'version': '4.9.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Selenium Team',
        'repo_url': 'https://github.com/SeleniumHQ/selenium'
    },
    {
        'library_name': 'BeautifulSoup',
        'version': '4.12.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'web scraping',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'BeautifulSoup Team',
        'repo_url': 'https://github.com/waylan/beautifulsoup'
    },
    {
        'library_name': 'Scrapy',
        'version': '2.8.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'web scraping',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Scrapy Team',
        'repo_url': 'https://github.com/scrapy/scrapy'
    },
    {
        'library_name': 'Pillow',
        'version': '9.5.0',
        'compatibility': 'Python',
        'license': 'HPND',
        'category': 'image processing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Pillow Team',
        'repo_url': 'https://github.com/python-pillow/Pillow'
    },
    {
        'library_name': 'OpenCV',
        'version': '4.7.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'computer vision',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'OpenCV Team',
        'repo_url': 'https://github.com/opencv/opencv'
    },
    {
        'library_name': 'PyQt',
        'version': '6.5.0',
        'compatibility': 'Python',
        'license': 'GPL',
        'category': 'gui',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Riverbank Computing',
        'repo_url': 'https://github.com/radekp/qt'
    },
    {
        'library_name': 'Tkinter',
        'version': '8.6',
        'compatibility': 'Python',
        'license': 'PSF',
        'category': 'gui',
        'known_vulnerabilities': '',
        'reputation': 7,
        'developer': 'Python Software Foundation',
        'repo_url': ''
    },
    {
        'library_name': 'Django REST Framework',
        'version': '3.14.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'api',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Django REST Framework Team',
        'repo_url': 'https://github.com/encode/django-rest-framework'
    },
    {
        'library_name': 'Jinja2',
        'version': '3.1.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'templating',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Pallets Team',
        'repo_url': 'https://github.com/pallets/jinja'
    },
    {
        'library_name': 'SQLite',
        'version': '3.41.0',
        'compatibility': 'Python',
        'license': 'Public Domain',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'SQLite Team',
        'repo_url': 'https://github.com/sqlite/sqlite'
    },
    {
        'library_name': 'Psycopg2',
        'version': '2.9.0',
        'compatibility': 'Python',
        'license': 'LGPL',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Psycopg Team',
        'repo_url': 'https://github.com/psycopg/psycopg2'
    },
    {
        'library_name': 'PyMySQL',
        'version': '1.0.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'PyMySQL Team',
        'repo_url': 'https://github.com/PyMySQL/PyMySQL'
    },
    {
        'library_name': 'MongoDB',
        'version': '4.3.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'MongoDB Team',
        'repo_url': 'https://github.com/mongodb/mongo-python-driver'
    },
    {
        'library_name': 'Elasticsearch',
        'version': '8.7.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'search',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Elasticsearch Team',
        'repo_url': 'https://github.com/elastic/elasticsearch-py'
    },
    {
        'library_name': 'Dask',
        'version': '2023.3.0',
        'compatibility': 'Python',
        'license': 'BSD',
        'category': 'parallel computing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Dask Team',
        'repo_url': 'https://github.com/dask/dask'
    },
    {
        'library_name': 'Airflow',
        'version': '2.6.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'workflow',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/airflow'
    },
    {
        'library_name': 'Streamlit',
        'version': '1.22.0',
        'compatibility': 'Python',
        'license': 'Apache 2.0',
        'category': 'web app',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Streamlit Team',
        'repo_url': 'https://github.com/streamlit/streamlit'
    },

    # ========== JAVA БИБЛИОТЕКИ ==========
    {
        'library_name': 'Hibernate',
        'version': '6.0.0',
        'compatibility': 'Java',
        'license': 'LGPL',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Red Hat',
        'repo_url': 'https://github.com/hibernate/hibernate-orm'
    },
    {
        'library_name': 'Spring Boot',
        'version': '3.0.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'VMware',
        'repo_url': 'https://github.com/spring-projects/spring-boot'
    },
    {
        'library_name': 'Spring Framework',
        'version': '6.0.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'framework',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'VMware',
        'repo_url': 'https://github.com/spring-projects/spring-framework'
    },
    {
        'library_name': 'Jackson',
        'version': '2.15.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'json processing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'FasterXML',
        'repo_url': 'https://github.com/FasterXML/jackson'
    },
    {
        'library_name': 'JUnit',
        'version': '5.9.0',
        'compatibility': 'Java',
        'license': 'Eclipse Public License',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'JUnit Team',
        'repo_url': 'https://github.com/junit-team/junit5'
    },
    {
        'library_name': 'Mockito',
        'version': '5.2.0',
        'compatibility': 'Java',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Mockito Team',
        'repo_url': 'https://github.com/mockito/mockito'
    },
    {
        'library_name': 'Log4j',
        'version': '2.20.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'logging',
        'known_vulnerabilities': 'CVE-2021-44228 (fixed in 2.17.0)',
        'reputation': 6,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/logging-log4j2'
    },
    {
        'library_name': 'SLF4J',
        'version': '2.0.0',
        'compatibility': 'Java',
        'license': 'MIT',
        'category': 'logging',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'SLF4J Team',
        'repo_url': 'https://github.com/qos-ch/slf4j'
    },
    {
        'library_name': 'Maven',
        'version': '3.9.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'build tool',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/maven'
    },
    {
        'library_name': 'Gradle',
        'version': '8.1.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'build tool',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Gradle Team',
        'repo_url': 'https://github.com/gradle/gradle'
    },
    {
        'library_name': 'Lombok',
        'version': '1.18.0',
        'compatibility': 'Java',
        'license': 'MIT',
        'category': 'productivity',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Lombok Team',
        'repo_url': 'https://github.com/projectlombok/lombok'
    },
    {
        'library_name': 'Apache Commons',
        'version': '3.12.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'utilities',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/commons-lang'
    },
    {
        'library_name': 'Guava',
        'version': '31.0.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'utilities',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Google',
        'repo_url': 'https://github.com/google/guava'
    },
    {
        'library_name': 'JPA',
        'version': '3.1.0',
        'compatibility': 'Java',
        'license': 'Eclipse Public License',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Eclipse Foundation',
        'repo_url': ''
    },
    {
        'library_name': 'JDBC',
        'version': '4.3',
        'compatibility': 'Java',
        'license': 'Oracle Binary Code License',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Oracle',
        'repo_url': ''
    },
    {
        'library_name': 'Apache Spark',
        'version': '3.4.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'big data',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/spark'
    },
    {
        'library_name': 'Kafka',
        'version': '3.4.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'messaging',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Apache Software Foundation',
        'repo_url': 'https://github.com/apache/kafka'
    },
    {
        'library_name': 'Elasticsearch Java Client',
        'version': '8.7.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'search',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Elasticsearch Team',
        'repo_url': 'https://github.com/elastic/elasticsearch-java'
    },
    {
        'library_name': 'Android SDK',
        'version': '33.0.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'mobile',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Google',
        'repo_url': ''
    },
    {
        'library_name': 'Spring Security',
        'version': '6.0.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'security',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'VMware',
        'repo_url': 'https://github.com/spring-projects/spring-security'
    },
    {
        'library_name': 'JWT',
        'version': '0.11.0',
        'compatibility': 'Java',
        'license': 'Apache 2.0',
        'category': 'security',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Auth0',
        'repo_url': 'https://github.com/auth0/java-jwt'
    },

    # ========== C# БИБЛИОТЕКИ ==========
    {
        'library_name': 'Entity Framework',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Microsoft',
        'repo_url': 'https://github.com/dotnet/efcore'
    },
    {
        'library_name': 'ASP.NET Core',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Microsoft',
        'repo_url': 'https://github.com/dotnet/aspnetcore'
    },
    {
        'library_name': 'Newtonsoft.Json',
        'version': '13.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'json processing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'James Newton-King',
        'repo_url': 'https://github.com/JamesNK/Newtonsoft.Json'
    },
    {
        'library_name': 'System.Text.Json',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'json processing',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Microsoft',
        'repo_url': ''
    },
    {
        'library_name': 'AutoMapper',
        'version': '12.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'object mapping',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'AutoMapper Team',
        'repo_url': 'https://github.com/AutoMapper/AutoMapper'
    },
    {
        'library_name': 'Moq',
        'version': '4.18.0',
        'compatibility': 'C#',
        'license': 'BSD',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Moq Team',
        'repo_url': 'https://github.com/moq/moq'
    },
    {
        'library_name': 'xUnit',
        'version': '2.4.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'xUnit Team',
        'repo_url': 'https://github.com/xunit/xunit'
    },
    {
        'library_name': 'NUnit',
        'version': '3.13.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'NUnit Team',
        'repo_url': 'https://github.com/nunit/nunit'
    },
    {
        'library_name': 'Serilog',
        'version': '2.12.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'logging',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Serilog Team',
        'repo_url': 'https://github.com/serilog/serilog'
    },
    {
        'library_name': 'NLog',
        'version': '5.1.0',
        'compatibility': 'C#',
        'license': 'BSD',
        'category': 'logging',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'NLog Team',
        'repo_url': 'https://github.com/NLog/NLog'
    },
    {
        'library_name': 'Dapper',
        'version': '2.0.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Dapper Team',
        'repo_url': 'https://github.com/DapperLib/Dapper'
    },
    {
        'library_name': 'Windows Forms',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'gui',
        'known_vulnerabilities': '',
        'reputation': 7,
        'developer': 'Microsoft',
        'repo_url': ''
    },
    {
        'library_name': 'WPF',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'gui',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Microsoft',
        'repo_url': ''
    },
    {
        'library_name': 'Unity',
        'version': '2022.3.0',
        'compatibility': 'C#',
        'license': 'Proprietary',
        'category': 'game development',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Unity Technologies',
        'repo_url': 'https://github.com/Unity-Technologies/UnityCsReference'
    },
    {
        'library_name': 'ML.NET',
        'version': '2.0.0',
        'compatibility': 'C#',
        'license': 'MIT',
        'category': 'machine learning',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Microsoft',
        'repo_url': 'https://github.com/dotnet/machinelearning'
    },
    {
        'library_name': 'SignalR',
        'version': '7.0.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'real-time',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Microsoft',
        'repo_url': 'https://github.com/SignalR/SignalR'
    },
    {
        'library_name': 'Polly',
        'version': '7.2.0',
        'compatibility': 'C#',
        'license': 'BSD',
        'category': 'resilience',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Polly Team',
        'repo_url': 'https://github.com/App-vNext/Polly'
    },
    {
        'library_name': 'MediatR',
        'version': '12.0.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'mediator pattern',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'MediatR Team',
        'repo_url': 'https://github.com/jbogard/MediatR'
    },
    {
        'library_name': 'FluentValidation',
        'version': '11.0.0',
        'compatibility': 'C#',
        'license': 'Apache 2.0',
        'category': 'validation',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'FluentValidation Team',
        'repo_url': 'https://github.com/FluentValidation/FluentValidation'
    },

    # ========== JAVASCRIPT БИБЛИОТЕКИ ==========
    {
        'library_name': 'Express.js',
        'version': '4.18.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'web framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Express.js Team',
        'repo_url': 'https://github.com/expressjs/express'
    },
    {
        'library_name': 'React',
        'version': '18.2.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'frontend framework',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Facebook',
        'repo_url': 'https://github.com/facebook/react'
    },
    {
        'library_name': 'Vue.js',
        'version': '3.3.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'frontend framework',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Vue.js Team',
        'repo_url': 'https://github.com/vuejs/vue'
    },
    {
        'library_name': 'Angular',
        'version': '16.0.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'frontend framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Google',
        'repo_url': 'https://github.com/angular/angular'
    },
    {
        'library_name': 'Node.js',
        'version': '18.15.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'runtime',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'OpenJS Foundation',
        'repo_url': 'https://github.com/nodejs/node'
    },
    {
        'library_name': 'Axios',
        'version': '1.4.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'http client',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Axios Team',
        'repo_url': 'https://github.com/axios/axios'
    },
    {
        'library_name': 'Lodash',
        'version': '4.17.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'utility library',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Lodash Team',
        'repo_url': 'https://github.com/lodash/lodash'
    },
    {
        'library_name': 'Moment.js',
        'version': '2.29.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'date manipulation',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Moment.js Team',
        'repo_url': 'https://github.com/moment/moment'
    },
    {
        'library_name': 'Date-fns',
        'version': '2.30.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'date manipulation',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Date-fns Team',
        'repo_url': 'https://github.com/date-fns/date-fns'
    },
    {
        'library_name': 'Jest',
        'version': '29.5.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Jest Team',
        'repo_url': 'https://github.com/jestjs/jest'
    },
    {
        'library_name': 'Mocha',
        'version': '10.2.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Mocha Team',
        'repo_url': 'https://github.com/mochajs/mocha'
    },
    {
        'library_name': 'Chai',
        'version': '4.3.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'testing',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Chai Team',
        'repo_url': 'https://github.com/chaijs/chai'
    },
    {
        'library_name': 'Webpack',
        'version': '5.80.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'bundler',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Webpack Team',
        'repo_url': 'https://github.com/webpack/webpack'
    },
    {
        'library_name': 'Babel',
        'version': '7.22.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'compiler',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Babel Team',
        'repo_url': 'https://github.com/babel/babel'
    },
    {
        'library_name': 'TypeScript',
        'version': '5.1.0',
        'compatibility': 'JavaScript',
        'license': 'Apache 2.0',
        'category': 'language',
        'known_vulnerabilities': '',
        'reputation': 10,
        'developer': 'Microsoft',
        'repo_url': 'https://github.com/microsoft/TypeScript'
    },
    {
        'library_name': 'Socket.io',
        'version': '4.6.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'real-time',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Socket.io Team',
        'repo_url': 'https://github.com/socketio/socket.io'
    },
    {
        'library_name': 'React Native',
        'version': '0.72.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'mobile',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Facebook',
        'repo_url': 'https://github.com/facebook/react-native'
    },
    {
        'library_name': 'Next.js',
        'version': '13.4.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Vercel',
        'repo_url': 'https://github.com/vercel/next.js'
    },
    {
        'library_name': 'Nuxt.js',
        'version': '3.6.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'framework',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Nuxt.js Team',
        'repo_url': 'https://github.com/nuxt/nuxt'
    },
    {
        'library_name': 'D3.js',
        'version': '7.8.0',
        'compatibility': 'JavaScript',
        'license': 'BSD',
        'category': 'data visualization',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'D3.js Team',
        'repo_url': 'https://github.com/d3/d3'
    },
    {
        'library_name': 'Chart.js',
        'version': '4.3.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'data visualization',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Chart.js Team',
        'repo_url': 'https://github.com/chartjs/Chart.js'
    },
    {
        'library_name': 'Three.js',
        'version': '0.152.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': '3d graphics',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Three.js Team',
        'repo_url': 'https://github.com/mrdoob/three.js'
    },
    {
        'library_name': 'Ramda.js',
        'version': '0.28.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'functional programming',
        'known_vulnerabilities': '',
        'reputation': 8,
        'developer': 'Ramda Team',
        'repo_url': 'https://github.com/ramda/ramda'
    },
    {
        'library_name': 'Redux',
        'version': '4.2.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'state management',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Redux Team',
        'repo_url': 'https://github.com/reduxjs/redux'
    },
    {
        'library_name': 'Mongoose',
        'version': '7.3.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Mongoose Team',
        'repo_url': 'https://github.com/Automattic/mongoose'
    },
    {
        'library_name': 'Sequelize',
        'version': '6.32.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'database',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Sequelize Team',
        'repo_url': 'https://github.com/sequelize/sequelize'
    },
    {
        'library_name': 'Passport.js',
        'version': '0.6.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'authentication',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Passport.js Team',
        'repo_url': 'https://github.com/jaredhanson/passport'
    },
    {
        'library_name': 'JWT (jsonwebtoken)',
        'version': '9.0.0',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'authentication',
        'known_vulnerabilities': '',
        'reputation': 9,
        'developer': 'Auth0',
        'repo_url': 'https://github.com/auth0/node-jsonwebtoken'
    },

    # ========== БИБЛИОТЕКИ С ПРОБЛЕМАМИ (для тестирования правил) ==========
    {
        'library_name': 'VulnerableLib',
        'version': '1.0.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'general',
        'known_vulnerabilities': 'CVE-2023-12345, CVE-2023-67890',
        'reputation': 3,
        'developer': 'Unknown',
        'repo_url': ''
    },
    {
        'library_name': 'OutdatedLib',
        'version': '0.5.0',
        'compatibility': 'Python',
        'license': 'GPL',
        'category': 'general',
        'known_vulnerabilities': '',
        'reputation': 4,
        'developer': 'Abandoned Developer',
        'repo_url': ''
    },
    {
        'library_name': 'ProprietaryLib',
        'version': '2.1.0',
        'compatibility': 'Java',
        'license': 'Proprietary',
        'category': 'enterprise',
        'known_vulnerabilities': '',
        'reputation': 7,
        'developer': 'Commercial Corp',
        'repo_url': ''
    },
    {
        'library_name': 'LowReputationLib',
        'version': '1.2.3',
        'compatibility': 'JavaScript',
        'license': 'MIT',
        'category': 'utility',
        'known_vulnerabilities': '',
        'reputation': 2,
        'developer': 'Unknown Developer',
        'repo_url': ''
    },
    {
        'library_name': 'UnmaintainedLib',
        'version': '0.8.0',
        'compatibility': 'Python',
        'license': 'MIT',
        'category': 'general',
        'known_vulnerabilities': '',
        'reputation': 3,
        'developer': 'Inactive Developer',
        'repo_url': ''
    }
]